name: Decoo chain deploy
on:
  workflow_dispatch:
  push:
    branches: [ mainnet ]

jobs:
  build-and-publish-decoo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: rustup install nightly-2021-01-11 && rustup default nightly-2021-01-11 && rustup target add wasm32-unknown-unknown --toolchain nightly-2021-01-11
      - run: cargo build --release && cp -f target/release/crust docker/crust/crust

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DECOO_PAT }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/crust/Dockerfile
          push: true
          tags: ghcr.io/decooio/decoo-crust:dev
